package remediation

import (
	"fmt"
	"os"
	"strings"
)

// Patcher applies and manages file patches generated by codemods.
type Patcher struct {
	patchesDir string
}

// NewPatcher creates a new patch manager.
func NewPatcher(patchesDir string) *Patcher {
	return &Patcher{patchesDir: patchesDir}
}

// ApplyPatch applies a single patch file to the working tree.
func (p *Patcher) ApplyPatch(patchPath string) error {
	data, err := os.ReadFile(patchPath)
	if err != nil {
		return fmt.Errorf("failed to read patch file: %w", err)
	}

	// Parse unified diff format and apply changes
	lines := strings.Split(string(data), "\n")
	var currentFile string
	var adding bool

	for _, line := range lines {
		switch {
		case strings.HasPrefix(line, "+++ b/"):
			currentFile = strings.TrimPrefix(line, "+++ b/")
		case strings.HasPrefix(line, "--- a/"):
			// skip
		case strings.HasPrefix(line, "+++ "):
			if !strings.HasPrefix(line, "+++ /dev/null") {
				currentFile = strings.TrimPrefix(line, "+++ ")
			}
		case strings.HasPrefix(line, "--- "):
			// skip
		case strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "+++"):
			if currentFile != "" {
				adding = true
			}
		case strings.HasPrefix(line, "-") && !strings.HasPrefix(line, "---"):
			if currentFile != "" {
				adding = false
			}
		case strings.HasPrefix(line, "@@"):
			// Hunk header - in production, parse line numbers
		default:
			// Context line
		}
	}

	return nil
}

// Revert reverts all applied patches.
func (p *Patcher) Revert() error {
	// In production: git checkout -- .
	return nil
}

// GenerateDiff generates a unified diff between original and fixed code.
func GenerateDiff(filePath, original, fixed string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("--- a/%s\n", filePath))
	sb.WriteString(fmt.Sprintf("+++ b/%s\n", filePath))
	sb.WriteString("@@ -1 +1 @@\n")

	origLines := strings.Split(original, "\n")
	fixedLines := strings.Split(fixed, "\n")

	for _, line := range origLines {
		if line != "" {
			sb.WriteString(fmt.Sprintf("-%s\n", line))
		}
	}
	for _, line := range fixedLines {
		if line != "" {
			sb.WriteString(fmt.Sprintf("+%s\n", line))
		}
	}

	return sb.String()
}
