package prbot

import (
	"bytes"
	"fmt"
	"time"
)

// CommitManager handles commit creation with structured messages.
type CommitManager struct{}

// NewCommitManager creates a commit manager.
func NewCommitManager() *CommitManager {
	return &CommitManager{}
}

// GenerateCommitMessage creates a structured commit message.
func (m *CommitManager) GenerateCommitMessage(files []string, fixCount int) string {
	var buf bytes.Buffer
	buf.WriteString("🔒 Auto-fix: security vulnerabilities remediation\n\n")
	buf.WriteString("Automated security fixes applied by DevSecOps pipeline.\n\n")

	// Count files
	fileCount := make(map[string]int)
	for _, f := range files {
		fileCount[f]++
	}

	buf.WriteString("| File | Changes |\n")
	buf.WriteString("|------|--------|\n")
	for file, count := range fileCount {
		buf.WriteString(fmt.Sprintf("| `%s` | %d fix(es) |\n", file, count))
	}

	buf.WriteString("\n---\n")
	buf.WriteString("*Generated by DevSecOps Auto-Remediation Pipeline*\n")
	buf.WriteString(fmt.Sprintf("*Fixes: %d | Timestamp: %s*\n", fixCount, time.Now().UTC().Format(time.RFC3339)))

	return buf.String()
}

// StageAndCommit stages all changes and creates a commit.
func (m *CommitManager) StageAndCommit(message string) error {
	if err := RunGit("add", "-A"); err != nil {
		return err
	}

	return RunGit("commit", "-m", message)
}

// HasChanges checks if there are unstaged or staged changes.
func (m *CommitManager) HasChanges() bool {
	err := RunGit("diff", "--cached", "--quiet")
	return err != nil // git diff --quiet returns 1 if there are changes
}

// RevertAll reverts all changes in the working tree.
func (m *CommitManager) RevertAll() error {
	return RunGit("checkout", "--", ".")
}
