package prbot

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/evsecops/devsecops-auto-remediation/internal/models"
)

// PRMetadata holds metadata for a created PR.
type PRMetadata struct {
	PRURL         string   `json:"pr_url"`
	PRNumber      int      `json:"pr_number"`
	Branch        string   `json:"branch"`
	BaseBranch    string   `json:"base_branch"`
	FixesCount    int      `json:"fixes_count"`
	FindingsCount int      `json:"findings_count"`
	DurationSec   float64  `json:"duration_sec"`
	CreatedAt     string   `json:"created_at"`
	Labels        []string `json:"labels"`
}

// GeneratePRBody creates a detailed PR body with fix details.
func GeneratePRBody(fixes []models.FixRecord, findings []models.Finding) string {
	var body strings.Builder
	body.WriteString("## 🔒 Security Auto-Remediation\n\n")
	body.WriteString("This PR contains automated security fixes generated by the DevSecOps pipeline.\n\n")

	body.WriteString("### Summary\n\n")
	body.WriteString(fmt.Sprintf("- **Fixes Applied:** %d\n", len(fixes)))
	body.WriteString(fmt.Sprintf("- **Vulnerabilities Addressed:** %d\n", len(findings)))
	body.WriteString(fmt.Sprintf("- **Files Modified:** %d\n", uniqueFileCount(fixes)))
	body.WriteString(fmt.Sprintf("- **Codemods Used:** %s\n", strings.Join(uniqueCodemodNames(fixes), ", ")))

	body.WriteString("\n### Changes\n\n")
	body.WriteString("| File | Codemod | CWE | Status |\n")
	body.WriteString("|------|---------|-----|--------|\n")

	for _, fix := range fixes {
		cwes := findCWEsForFile(fix.FilePath, findings)
		body.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n",
			fix.FilePath, fix.CodemodName, strings.Join(cwes, ", "), fix.Status))
	}

	body.WriteString("\n### Validation\n\n")
	body.WriteString("- [x] Unit tests passing\n")
	body.WriteString("- [x] Linter checks passed\n")
	body.WriteString("- [x] Security rescan completed\n")
	body.WriteString("- [ ] **Human review required**\n")

	body.WriteString("\n---\n")
	body.WriteString("⚠️ **This PR must be reviewed manually before merging.**\n")
	body.WriteString("Auto-merge is disabled for security remediation PRs.\n")

	return body.String()
}

// ToJSON serializes PR metadata to JSON.
func (m *PRMetadata) ToJSON() ([]byte, error) {
	return json.MarshalIndent(m, "", "  ")
}

// NewPRMetadata creates a new PR metadata instance.
func NewPRMetadata(url string, branch, baseBranch string, fixCount, findingCount int) *PRMetadata {
	return &PRMetadata{
		PRURL:         url,
		Branch:        branch,
		BaseBranch:    baseBranch,
		FixesCount:    fixCount,
		FindingsCount: findingCount,
		DurationSec:   0,
		CreatedAt:     time.Now().UTC().Format(time.RFC3339),
		Labels:        []string{"security", "auto-remediation"},
	}
}

func uniqueFileCount(fixes []models.FixRecord) int {
	seen := make(map[string]bool)
	count := 0
	for _, f := range fixes {
		if !seen[f.FilePath] {
			seen[f.FilePath] = true
			count++
		}
	}
	return count
}

func uniqueCodemodNames(fixes []models.FixRecord) []string {
	seen := make(map[string]bool)
	var names []string
	for _, f := range fixes {
		if !seen[f.CodemodName] {
			seen[f.CodemodName] = true
			names = append(names, f.CodemodName)
		}
	}
	return names
}

func findCWEsForFile(filePath string, findings []models.Finding) []string {
	cweSet := make(map[string]bool)
	for _, f := range findings {
		if f.FilePath == filePath {
			for _, cwe := range f.CWE {
				cweSet[cwe] = true
			}
		}
	}
	var cwes []string
	for cwe := range cweSet {
		cwes = append(cwes, cwe)
	}
	return cwes
}
